version: '3'
    
networks:
  test_network:
    driver: bridge

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - test_network
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      - CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
    volumes:
      - ./test/test-results:/persistence/test/test-results
    depends_on:
      - azurite
    networks:
      - test_network
    #command: ["tail", "-f", "/dev/null"]
    command: ["python3", "-m", "pytest", "--junitxml=test-results/pytest_results.xml", "persistence-test.py"]