FROM python:latest

RUN mkdir /persistence
WORKDIR /persistence

RUN mkdir test
RUN mkdir test/data


COPY test/requirements.txt test/
COPY requirements.txt .

# Install test requirements
RUN pip install -r test/requirements.txt --user

# Install service requirements
RUN pip install -r requirements.txt --user

COPY test/persistence-test.py test/
COPY test/__init__.py test/__init__.py

COPY __init__.py .
COPY main.py .


WORKDIR /persistence/test
#CMD ["tail", "-f", "/dev/null"]
CMD ["python3", "-m", "pytest", "persistence-test.py"]
