services:
  angular_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mlaas-service-frontend:latest
    ports:
      - "4200:4200"
    environment:
      - BACKEND_API_PORT=5000;BACKEND_API_URL=http://localhost
