version: '3.5'

networks:
  test_network:
    driver: bridge

services:
  serving-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: mlaas-service-serving:latest
    ports:
      - "5001:5001"
    networks:
      - test_network