apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: apline:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azurite-secret
              key: CONNECTION_STRING
