apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/austriandatalab/ml-as-a-service:feature-frontend
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
