version: '3.5'
    
networks:
  test_network:
    driver: bridge

services:
  serving-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8501:8501" # this doesnt affect the ports within the docker network
    networks:
      - test_network