version: '2'
services:
  persistence-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1919:5000" # this doesnt affect the ports within the docker network
    networks:
      - test_network

  test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - ./test/test-results:/app/test/test-results
    #command: ["tail", "-f", "/dev/null"]
    command: ["python3", "-m", "pytest", "--junitxml=test-results/pytest_results.xml", "persistence-test.py"]
    

networks:
  test_network:
    driver: bridge